name: Issue Info
on:
  issues:
    types: [opened]
  workflow_dispatch
jobs:
  IssueCreated:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: echo ${{ toJSON(github.event) }}